# Generated by Django 5.2.10 on 2026-02-05 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_alter_account_id_alter_transaction_id_loan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='remarks',
        ),
        migrations.AddField(
            model_name='loan',
            name='balance_remaining',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='loan',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='pending_repayment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loan',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankapp.account'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='approved_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='loan',
            name='scheme',
            field=models.CharField(choices=[('Personal', 'Personal'), ('Car', 'Car'), ('Education', 'Education')], max_length=20),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
